export type SettingFieldType = 'string' | 'number' | 'boolean' | 'json';

export interface SettingField {
  key: string;
  env: string | null;
  path: string;
  type: SettingFieldType;
  label: string;
  section: string;
  editable: boolean;
  secret?: boolean;
  help?: string;
}

const field = (value: SettingField): SettingField => value;

export const APP_SETTING_FIELDS: SettingField[] = [
  field({
    key: 'port',
    env: 'PORT',
    path: 'server.port',
    type: 'number',
    label: 'API Port',
    section: 'System',
    editable: false,
    help: 'HTTP port used by the Nest backend.',
  }),
  field({
    key: 'databaseUrl',
    env: 'DATABASE_URL',
    path: 'database.url',
    type: 'string',
    label: 'Database URL',
    section: 'System',
    editable: false,
    secret: true,
    help: 'Bootstrap connection string for PostgreSQL.',
  }),
  field({
    key: 'databaseSsl',
    env: 'DATABASE_SSL',
    path: 'database.ssl',
    type: 'boolean',
    label: 'Database SSL',
    section: 'System',
    editable: false,
  }),
  field({
    key: 'typeormSynchronize',
    env: 'TYPEORM_SYNCHRONIZE',
    path: 'database.synchronize',
    type: 'boolean',
    label: 'TypeORM Synchronize',
    section: 'System',
    editable: false,
  }),
  field({
    key: 'dashboardAllowedWallet',
    env: 'DASHBOARD_ALLOWED_WALLET',
    path: 'auth.allowedWallet',
    type: 'string',
    label: 'Dashboard Allowed Wallet',
    section: 'System',
    editable: false,
    help: 'Only this wallet address can sign in to the dashboard.',
  }),
  field({
    key: 'dashboardSessionTtlHours',
    env: 'DASHBOARD_SESSION_TTL_HOURS',
    path: 'auth.sessionTtlHours',
    type: 'number',
    label: 'Dashboard Session TTL Hours',
    section: 'System',
    editable: false,
  }),
  field({
    key: 'voiceAlertsEnabled',
    env: null,
    path: 'dashboard.voiceAlertsEnabled',
    type: 'boolean',
    label: 'Voice Alerts Enabled',
    section: 'Dashboard',
    editable: true,
    help: 'Persists the dashboard voice alert toggle across refreshes.',
  }),
  field({
    key: 'liveTradingEnabled',
    env: 'LIVE_TRADING_ENABLED',
    path: 'execution.enabled',
    type: 'boolean',
    label: 'Live Trading Enabled',
    section: 'Execution',
    editable: true,
    help: 'Arms or disarms real order execution.',
  }),
  field({
    key: 'allowMainnetTrading',
    env: 'ALLOW_MAINNET_TRADING',
    path: 'execution.allowMainnet',
    type: 'boolean',
    label: 'Allow Mainnet Trading',
    section: 'Execution',
    editable: true,
    help: 'Second confirmation gate required for live mainnet execution.',
  }),
  field({
    key: 'hyperliquidPrivateKey',
    env: 'HYPERLIQUID_PRIVATE_KEY',
    path: 'hyperliquid.privateKey',
    type: 'string',
    label: 'API Wallet Private Key',
    section: 'Exchange',
    editable: true,
    secret: true,
    help: 'API wallet private key (agent wallet) — used to sign orders. Never your main wallet key.',
  }),
  field({
    key: 'hyperliquidAccountAddress',
    env: 'HYPERLIQUID_ACCOUNT_ADDRESS',
    path: 'hyperliquid.accountAddress',
    type: 'string',
    label: 'Main Account Address',
    section: 'Exchange',
    editable: true,
    help: 'Your main Hyperliquid account address (0x...) — used for balance and position queries.',
  }),
  field({
    key: 'hyperliquidTestnet',
    env: 'HYPERLIQUID_TESTNET',
    path: 'hyperliquid.testnet',
    type: 'boolean',
    label: 'Testnet Mode',
    section: 'Exchange',
    editable: true,
    help: 'Switch between testnet and mainnet on next restart.',
  }),
  field({
    key: 'hyperliquidMarketOrderSlippage',
    env: null,
    path: 'hyperliquid.marketOrderSlippage',
    type: 'number',
    label: 'Market Order Slippage',
    section: 'Exchange',
    editable: true,
    help: 'IOC market-order slippage as a decimal fraction. Example: 0.005 = 0.5%, 0.01 = 1%.',
  }),
  field({
    key: 'hyperliquidMinOrderBufferPercent',
    env: null,
    path: 'hyperliquid.minOrderBufferPercent',
    type: 'number',
    label: 'Exchange Min Buffer %',
    section: 'Exchange',
    editable: true,
    help: 'Extra percentage buffer above Hyperliquid\'s perp minimum to survive slippage and size rounding. Example: 2 means a $10 perp minimum is sent as at least about $10.20 on the final wire order.',
  }),
  field({
    key: 'hyperliquidExchangeMinOrderNotional',
    env: null,
    path: 'hyperliquid.exchangeMinOrderNotional',
    type: 'number',
    label: 'Exchange Min Order Notional',
    section: 'Exchange',
    editable: true,
    help: 'Minimum notional the bot targets before sending a perp order. Keep this aligned with the exchange rule if Hyperliquid changes its minimum.',
  }),
  field({
    key: 'hyperliquidMaxEntrySpreadBps',
    env: null,
    path: 'hyperliquid.maxEntrySpreadBps',
    type: 'number',
    label: 'Max Entry Spread Bps',
    section: 'Exchange',
    editable: true,
    help: 'Skip new entries when the live bid/ask spread is wider than this many basis points.',
  }),
  field({
    key: 'hyperliquidMaxEntrySlippageBps',
    env: null,
    path: 'hyperliquid.maxEntrySlippageBps',
    type: 'number',
    label: 'Max Entry Slippage Bps',
    section: 'Exchange',
    editable: true,
    help: 'Skip new entries when top-of-book depth implies more taker slippage than this many basis points for the intended size.',
  }),
  field({
    key: 'hyperliquidMaxWsSilenceSeconds',
    env: null,
    path: 'hyperliquid.maxWsSilenceSeconds',
    type: 'number',
    label: 'Max WS Silence Seconds',
    section: 'Exchange',
    editable: true,
    help: 'Refuse fresh entries when Hyperliquid websocket mids have been silent longer than this threshold.',
  }),
  field({
    key: 'hyperliquidApiUrl',
    env: 'HYPERLIQUID_API_URL',
    path: 'hyperliquid.apiUrl',
    type: 'string',
    label: 'API URL',
    section: 'Exchange',
    editable: true,
  }),
  field({
    key: 'hyperliquidWsUrl',
    env: 'HYPERLIQUID_WS_URL',
    path: 'hyperliquid.wsUrl',
    type: 'string',
    label: 'WebSocket URL',
    section: 'Exchange',
    editable: true,
  }),
  field({
    key: 'initialCapital',
    env: 'INITIAL_CAPITAL',
    path: 'capital.initial',
    type: 'number',
    label: 'Initial Capital',
    section: 'Capital',
    editable: true,
  }),
  field({
    key: 'maxConcurrentPositions',
    env: 'MAX_CONCURRENT_POSITIONS',
    path: 'capital.maxConcurrentPositions',
    type: 'number',
    label: 'Max Concurrent Positions',
    section: 'Capital',
    editable: true,
  }),
  field({
    key: 'leverage',
    env: 'DEFAULT_LEVERAGE',
    path: 'capital.leverage',
    type: 'number',
    label: 'Default Leverage',
    section: 'Capital',
    editable: true,
    help: 'Fallback leverage used when a score-specific leverage is not set.',
  }),
  field({
    key: 'leverageScore2',
    env: 'LEVERAGE_SCORE_2',
    path: 'capital.leverageScore2',
    type: 'number',
    label: 'Leverage For Score 2',
    section: 'Capital',
    editable: true,
    help: 'Leverage for smaller, lower-conviction setups. Lower values support the many-small-trades strategy.',
  }),
  field({
    key: 'leverageScore3',
    env: 'LEVERAGE_SCORE_3',
    path: 'capital.leverageScore3',
    type: 'number',
    label: 'Leverage For Score 3',
    section: 'Capital',
    editable: true,
    help: 'Leverage for medium-conviction setups.',
  }),
  field({
    key: 'leverageScore4',
    env: 'LEVERAGE_SCORE_4',
    path: 'capital.leverageScore4',
    type: 'number',
    label: 'Leverage For Score 4+',
    section: 'Capital',
    editable: true,
    help: 'Leverage for the strongest confirmed setups.',
  }),
  field({
    key: 'minOrderNotional',
    env: 'MIN_ORDER_NOTIONAL',
    path: 'capital.minOrderNotional',
    type: 'number',
    label: 'Strategy Min Order Notional',
    section: 'Capital',
    editable: true,
    help: 'Internal strategy floor in USDC notional. Signals smaller than this are bumped up to at least this size first. Live Hyperliquid perp orders can still be raised further to satisfy the exchange minimum and buffer.',
  }),
  field({
    key: 'marginScore2',
    env: 'MARGIN_SCORE_2',
    path: 'capital.marginScore2',
    type: 'number',
    label: 'Margin For Score 2',
    section: 'Capital',
    editable: true,
  }),
  field({
    key: 'marginScore3',
    env: 'MARGIN_SCORE_3',
    path: 'capital.marginScore3',
    type: 'number',
    label: 'Margin For Score 3',
    section: 'Capital',
    editable: true,
  }),
  field({
    key: 'marginScore4',
    env: 'MARGIN_SCORE_4',
    path: 'capital.marginScore4',
    type: 'number',
    label: 'Margin For Score 4',
    section: 'Capital',
    editable: true,
  }),
  field({
    key: 'freeCollateralBufferUsd',
    env: null,
    path: 'capital.freeCollateralBufferUsd',
    type: 'number',
    label: 'Free Collateral Buffer USD',
    section: 'Capital',
    editable: true,
    help: 'Minimum collateral to leave unused after opening a new trade. Prevents exchange-side insufficient margin rejections when funds are already reserved.',
  }),
  field({
    key: 'stopLossPercent',
    env: 'STOP_LOSS_PERCENT',
    path: 'exits.stopLossPercent',
    type: 'number',
    label: 'Stop Loss %',
    section: 'Exits',
    editable: true,
  }),
  field({
    key: 'tp1Percent',
    env: 'TP1_PERCENT',
    path: 'exits.tp1Percent',
    type: 'number',
    label: 'TP1 %',
    section: 'Exits',
    editable: true,
  }),
  field({
    key: 'tp2Percent',
    env: 'TP2_PERCENT',
    path: 'exits.tp2Percent',
    type: 'number',
    label: 'TP2 %',
    section: 'Exits',
    editable: true,
  }),
  field({
    key: 'tp1ClosePercent',
    env: null,
    path: 'exits.tp1ClosePercent',
    type: 'number',
    label: 'TP1 Close %',
    section: 'Exits',
    editable: true,
    help: 'Percent of the original position size closed at TP1.',
  }),
  field({
    key: 'tp2ClosePercent',
    env: null,
    path: 'exits.tp2ClosePercent',
    type: 'number',
    label: 'TP2 Close %',
    section: 'Exits',
    editable: true,
    help: 'Percent of the original position size closed at TP2.',
  }),
  field({
    key: 'tp3ClosePercent',
    env: null,
    path: 'exits.tp3ClosePercent',
    type: 'number',
    label: 'TP3 Close %',
    section: 'Exits',
    editable: true,
    help: 'Percent of the original position size reserved for the final trailing-stop exit.',
  }),
  field({
    key: 'trailingStopPercent',
    env: 'TRAILING_STOP_PERCENT',
    path: 'exits.trailingStopPercent',
    type: 'number',
    label: 'Trailing Stop %',
    section: 'Exits',
    editable: true,
  }),
  field({
    key: 'maxHoldHours',
    env: 'MAX_HOLD_HOURS',
    path: 'exits.maxHoldHours',
    type: 'number',
    label: 'Max Hold Hours',
    section: 'Exits',
    editable: true,
  }),
  field({
    key: 'volatilityStopPercent',
    env: null,
    path: 'exits.volatilityStopPercent',
    type: 'number',
    label: 'Volatility Stop %',
    section: 'Exits',
    editable: true,
  }),
  field({
    key: 'dailyLossLimit',
    env: 'DAILY_LOSS_LIMIT',
    path: 'risk.dailyLossLimit',
    type: 'number',
    label: 'Daily Loss Limit',
    section: 'Risk',
    editable: true,
  }),
  field({
    key: 'weeklyLossLimit',
    env: 'WEEKLY_LOSS_LIMIT',
    path: 'risk.weeklyLossLimit',
    type: 'number',
    label: 'Weekly Loss Limit',
    section: 'Risk',
    editable: true,
  }),
  field({
    key: 'emergencyCapitalFloor',
    env: 'EMERGENCY_CAPITAL_FLOOR',
    path: 'risk.emergencyCapitalFloor',
    type: 'number',
    label: 'Emergency Capital Floor',
    section: 'Risk',
    editable: true,
  }),
  field({
    key: 'consecutiveLossPause2h',
    env: null,
    path: 'risk.consecutiveLossPause2h',
    type: 'number',
    label: 'Consecutive Loss Pause 2H',
    section: 'Risk',
    editable: true,
  }),
  field({
    key: 'consecutiveLossPauseDay',
    env: null,
    path: 'risk.consecutiveLossPauseDay',
    type: 'number',
    label: 'Consecutive Loss Pause Day',
    section: 'Risk',
    editable: true,
  }),
  field({
    key: 'fundingRateMax',
    env: 'FUNDING_RATE_MAX',
    path: 'filters.fundingRateMax',
    type: 'number',
    label: 'Funding Rate Max',
    section: 'Filters',
    editable: true,
  }),
  field({
    key: 'minMarketCap',
    env: 'MIN_MARKET_CAP',
    path: 'filters.minMarketCap',
    type: 'number',
    label: 'Min Market Cap',
    section: 'Filters',
    editable: true,
  }),
  field({
    key: 'minTokenAgeDays',
    env: 'MIN_TOKEN_AGE_DAYS',
    path: 'filters.minTokenAgeDays',
    type: 'number',
    label: 'Min Token Age Days',
    section: 'Filters',
    editable: true,
  }),
  field({
    key: 'minDayVolume',
    env: null,
    path: 'filters.minDayVolume',
    type: 'number',
    label: 'Min Day Volume',
    section: 'Filters',
    editable: true,
    help: 'Only track Hyperliquid perp markets with at least this much 24h notional volume.',
  }),
  field({
    key: 'minOpenInterest',
    env: null,
    path: 'filters.minOpenInterest',
    type: 'number',
    label: 'Min Open Interest',
    section: 'Filters',
    editable: true,
    help: 'Only track Hyperliquid perp markets with at least this much open interest.',
  }),
  field({
    key: 'maxPriceChange2h',
    env: null,
    path: 'filters.maxPriceChange2h',
    type: 'number',
    label: 'Max Price Change 2H',
    section: 'Filters',
    editable: true,
  }),
  field({
    key: 'consecutiveLossFilter',
    env: null,
    path: 'filters.consecutiveLossFilter',
    type: 'number',
    label: 'Consecutive Loss Filter',
    section: 'Filters',
    editable: true,
  }),
  field({
    key: 'scanIntervalSeconds',
    env: 'SCAN_INTERVAL_SECONDS',
    path: 'scan.intervalSeconds',
    type: 'number',
    label: 'Scan Interval Seconds',
    section: 'Scanning',
    editable: true,
  }),
  field({
    key: 'candleLookback',
    env: null,
    path: 'scan.candleLookback',
    type: 'number',
    label: 'Candle Lookback',
    section: 'Scanning',
    editable: true,
  }),
  field({
    key: 'maxTrackedTokens',
    env: 'MAX_TRACKED_TOKENS',
    path: 'scan.maxTrackedTokens',
    type: 'number',
    label: 'Max Tracked Tokens',
    section: 'Scanning',
    editable: true,
  }),
  field({
    key: 'volumeSpikeMultiplier',
    env: 'VOLUME_SPIKE_MULTIPLIER',
    path: 'patterns.volumeSpikeMultiplier',
    type: 'number',
    label: 'Volume Spike Multiplier',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'volumeSpikeMaxPriceChange',
    env: 'VOLUME_SPIKE_MAX_PRICE_CHANGE',
    path: 'patterns.volumeSpikeMaxPriceChange',
    type: 'number',
    label: 'Volume Spike Max Price Change',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'flagSharpMovePercent',
    env: 'FLAG_SHARP_MOVE_PERCENT',
    path: 'patterns.flagSharpMovePercent',
    type: 'number',
    label: 'Flag Sharp Move %',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'flagConsolidationSpread',
    env: 'FLAG_CONSOLIDATION_SPREAD',
    path: 'patterns.flagConsolidationSpread',
    type: 'number',
    label: 'Flag Consolidation Spread',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'accumulationRangePercent',
    env: 'ACCUMULATION_RANGE_PERCENT',
    path: 'patterns.accumulationRangePercent',
    type: 'number',
    label: 'Accumulation Range %',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'accumulationBreakoutVolume',
    env: 'ACCUMULATION_BREAKOUT_VOLUME',
    path: 'patterns.accumulationBreakoutVolume',
    type: 'number',
    label: 'Accumulation Breakout Volume',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'fibLevels',
    env: null,
    path: 'patterns.fibLevels',
    type: 'json',
    label: 'Fibonacci Levels',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'fibTolerancePercent',
    env: null,
    path: 'patterns.fibTolerancePercent',
    type: 'number',
    label: 'Fibonacci Tolerance %',
    section: 'Patterns',
    editable: true,
  }),
  field({
    key: 'solBearThresholdPercent',
    env: 'SOL_BEAR_THRESHOLD_PERCENT',
    path: 'market.solBearThresholdPercent',
    type: 'number',
    label: 'SOL Bear Threshold %',
    section: 'Market',
    editable: true,
  }),
  field({
    key: 'btcBearThresholdPercent',
    env: 'BTC_BEAR_THRESHOLD_PERCENT',
    path: 'market.btcBearThresholdPercent',
    type: 'number',
    label: 'BTC Bear Threshold %',
    section: 'Market',
    editable: true,
  }),
  field({
    key: 'bullMarketThresholdPercent',
    env: 'BULL_MARKET_THRESHOLD_PERCENT',
    path: 'market.bullMarketThresholdPercent',
    type: 'number',
    label: 'Bull Market Threshold %',
    section: 'Market',
    editable: true,
  }),
];

export const APP_SETTING_FIELD_BY_KEY = new Map(APP_SETTING_FIELDS.map((entry) => [entry.key, entry]));
export const APP_SETTING_FIELD_BY_PATH = new Map(APP_SETTING_FIELDS.map((entry) => [entry.path, entry]));
